"""add user_id foreign key to urls

Revision ID: 443251802067
Revises: cdafc0f830b2
Create Date: 2026-09-13 19:54:47.107653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '443251802067'
down_revision: Union[str, Sequence[str], None] = 'cdafc0f830b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_urls_user_id'), 'urls', ['user_id'], unique=False)
    op.create_foreign_key(None, 'urls', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'urls', type_='foreignkey')
    op.drop_index(op.f('ix_urls_user_id'), table_name='urls')
    op.drop_column('urls', 'user_id')
    # ### end Alembic commands ###
